require'lspkind'.init({
   with_text = true,
   symbol_map = {
     Text = '',
     Method = '',
     Function = '',
     Constructor = '',
     Variable = '[]',
     Class = '',
     Interface = '蘒',
     Module = '',
     Property = '',
     Unit = '',
     Value = '',
     Enum = '了',
     Keyword = '',
     Snippet = '﬌',
     Color = '',
     File = '',
     Folder = '',
     EnumMember = '',
     Constant = '',
     Struct = '',
   },
})
